apiVersion: v1
kind: Pod
metadata:
  name: kyu-pytorch-cub-sequential-binbash-long-resnet101-4
  labels:
    user: kyu
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 168151
    fsGroup: 11169
  volumes:
    - name: cvlabdata2
      persistentVolumeClaim:
        claimName: pv-cvlabdata2
    - name: cvlabdata1
      persistentVolumeClaim:
        claimName: pv-cvlabdata1
    - name: cvlabsrc1
      persistentVolumeClaim:
        claimName: pv-cvlabsrc1
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
  containers:
  - name:  kyu-pytorch-imagenet-gpu
    image: ic-registry.epfl.ch/cvlab/pytorch-imagenet:v1.0.2
    command: ['/bin/bash']
    args: ['./bash/cub-debug-resume.sh', '4']
    resources:
      limits:
        cpu: 6
        nvidia.com/gpu: 1 # requesting 1 GPU
      requests:
        memory: 12Gi
    workingDir: /home/kyu/.pycharm/foso
    env:
      - name: HOME
        value: /home/kyu
      - name: PYTHONPATH
        value: /home/kyu/.pycharm/foso:/home/kyu/.pycharm/foso/source:$PYTHONPATH
    volumeMounts:
      - mountPath: /cvlabdata1
        name: cvlabdata1
      - mountPath: /cvlabsrc1
        name: cvlabsrc1
      - mountPath: /cvlabdata2
        name: cvlabdata2
      - mountPath: /home/kyu
        name: cvlabdata2
        subPath: home/kyu
      - mountPath: /dev/shm
        name: dshm

