apiVersion: v1
kind: Pod
metadata:
  name: <your-pod-name>
  labels:
    user: <your-name>
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: <your-uid>
    fsGroup: 11169
  containers:
  - name:  ubuntu-gpu
    image: ic-registry.epfl.ch/cvlab/<your-docker-image-tag>
    command:
      - sleep
      - "60"
    resources:
      limits:
        nvidia.com/gpu: 0 # requesting 1 GPU
    volumeMounts:
      - mountPath: /cvlabdata2
        name: cvlabdata2
  volumes:
    - name: cvlabdata2
      persistentVolumeClaim:
        claimName: pv-cvlabdata2
    - name: cvlabsrc1
      persistentVolumeClaim:
        claimName: pv-cvlabsrc1