apiVersion: v1
kind: Pod
metadata:
  labels:
    runUser: kyu
    user: kyu
  name: kyu-pytorch-imagenet-training-debug-timeout-1
spec:
  containers:
  - args:
    - python test.py
    command:
    - /bin/bash
    - -c
    env:
    - name: HOME
      value: /home/kyu
    - name: PYTHONPATH
      value: /home/kyu/.pycharm/foso:/home/kyu/.pycharm/foso/source:$PYTHONPATH
    image: ic-registry.epfl.ch/cvlab/pytorch-imagenet:v0.1
    name: kyu-pytorch-imagenet-gpu
    resources:
      limits:
        nvidia.com/gpu: 0
      requests:
        memory: 12Gi
    volumeMounts:
    - mountPath: /cvlabdata1
      name: cvlabdata1
    - mountPath: /cvlabdata2
      name: cvlabdata2
    - mountPath: /home/kyu
      name: cvlabdata2
      subPath: home/kyu
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /cvlabsrc1
      name: cvlabsrc1
    workingDir: /home/kyu/.pycharm/foso
  restartPolicy: Never
  securityContext:
    fsGroup: 11169
    runAsUser: 168151
  volumes:
  - name: cvlabdata2
    persistentVolumeClaim:
      claimName: pv-cvlabdata2
  - name: cvlabdata1
    persistentVolumeClaim:
      claimName: pv-cvlabdata1
  - emptyDir:
      medium: Memory
      sizeLimit: 8Gi
    name: dshm
  - name: cvlabsrc1
    persistentVolumeClaim:
      claimName: pv-cvlabsrc1
